libs/quadkey.js
Adds support to generate quadkeys for high zoom levels (should be ok up to z52).
Removes all the pixel logic since it's unnecessary .
=> Quadkey high zoom support

libs/quadkey.js
Something like 311131313 got a x_max of 180.00000000000003, which is just sligthly
over the antimeridian, so when reading the GeoJSON BQ translated it to ~ -180 which
created a line across the world in the opposite direction of what we want
=> Ensure geographies don't go over the antimeridian

.github/workflows/ci.yml, skel/bq/test/skel_integration.js
Applies several fixes that appear in multiple PRs and some extra necessary to improve things overall:
* Avoid using datasets starting with numbers (they are fragile in BigQuery, as they work in some situations but not in others).
* Use node 14.
* Use query() instead of createQueryJob(). Query() has only one point of failure, while createQueryJob() and friends might fail in different functions for the exact same query (specially with procedures).
=> Improve CI

quadkey/CHANGELOG.md, quadkey/bq/sql/TOPARENT.sql, quadkey/bq/test/parent_integration.js
I'm updating toparent to its sql version which is way faster.
Could have done more checks but this should be enough for covering the major issues without decreasing performance too much. The main difference with the previous is that this version accepts getting a quadint with the same resolution that the sent one and it would return the same value.
For instance:
-- bqcarto.quadkey.QUADINT_FROMZXY(3,1,1) -> 291
bqcarto.quadkey.TOPARENT(291, 3) -> 291
Closes #63 
The test will fail until the next PR is merged:
https://github.com/CartoDB/carto-spatial-extension/pull/65
=> update function and tests

constructors/CHANGELOG.md, constructors/bq/Makefile, constructors/bq/doc/REFERENCE.md, constructors/bq/sql/ST_TILEENVELOPE.sql, constructors/bq/test/tileenvelope_integration.js, tools/setool/lib/create-module/generator.js
The original PostGIS function (https://postgis.net/docs/ST_TileEnvelope.html) also includes an extra `margin` parameter to grow a tile by the given percentage. As we stated in Slack, the current implementation uses just the (x,y,z) index to extract the polygon but in case the `margin`parameter is further required, this implementation is not valid and we must go with a previous step for extracting the bounding box. We can use something like this:
```sql
SELECT `@@BQ_PROJECTID@@.@@BQ_DATASET_CONSTRUCTORS@@.ST_MAKEENVELOPE`(
bounds[OFFSET(0)],
bounds[OFFSET(1)],
bounds[OFFSET(2)],
bounds[OFFSET(3)]
)
FROM (
SELECT `@@BQ_PROJECTID@@.@@BQ_DATASET_QUADKEY@@.BBOX`(
`@@BQ_PROJECTID@@.@@BQ_DATASET_QUADKEY@@.QUADINT_FROMZXY`(zoomLevel,xTile,yTile)) AS bounds
)
```
The problem is the …
=> Added ST_TILEENVELOPE to "constructors" module

common/snowflake/Makefile, modules/accessors/snowflake/sql/_SHARE_REMOVE.sql, modules/constructors/snowflake/sql/_SHARE_REMOVE.sql, modules/h3/snowflake/sql/_SHARE_REMOVE.sql, modules/measurements/snowflake/sql/_SHARE_REMOVE.sql, modules/placekey/snowflake/sql/_SHARE_REMOVE.sql, modules/processing/snowflake/sql/_SHARE_REMOVE.sql, modules/quadkey/snowflake/sql/_SHARE_REMOVE.sql, modules/s2/snowflake/sql/_SHARE_REMOVE.sql, modules/transformations/snowflake/sql/_SHARE_REMOVE.sql, tools/setool/lib/create-module/generator.js
- We were losing links between functions and shares on each deployment. We are using the `ADVANCED_SPATIAL_EXTENSION` share in the marketplace and each time we deploy core very likely the links to that share were broken. Now each time we deploy core it will also add the core functions to the `ADVANCED_SPATIAL_EXTENSION` share so the link shouldn't be lost anymore. Would be awesome as well to request the SF team for a `COPY GRANTS` option.
- I use this PR also to add `USE ROLE ACCOUNTADMIN` in the `share-remove` since it should be crashing.
=> Allow sharing with multiple shares in Snowflake

modules/constructors/bigquery/sql/ST_MAKEENVELOPE.sql, modules/quadkey/bigquery/sql/ST_BOUNDARY.sql
ST_MAKEPOLYGON + ST_MAKELINE + ST_GEOGPOINT reduce computing time by 20% and workers time by 50% in comparison to WKT parsing
=> Use ST_MAKEPOLYGON ST_MAKELINE ST_GEOGPOINT instead of ST_GeogFromText

common/redshift/Makefile
The libraries were removed from S3 but not from redshift.
=> Clean redshift library on test-integration-full

modules/quadkey/bigquery/CHANGELOG.md, modules/quadkey/bigquery/doc/VERSION.md, modules/quadkey/bigquery/lib/quadkey.js, modules/quadkey/bigquery/package.json, modules/quadkey/snowflake/CHANGELOG.md, modules/quadkey/snowflake/doc/VERSION.md, modules/quadkey/snowflake/lib/quadkey.js, modules/quadkey/snowflake/package.json
Depending on the resolution and execution this has more or less impact but in general there was some performance improvement.
For instance, running:
```
select bqcarto.quadkey.ST_ASQUADINT_POLYFILL(ST_GEOGFROMGEOJSON('{ "type": "MultiPolygon", "coordinates": [ [ [ [-176.484375, 84.7383871209534], [-176.484375, 84.7060489350415], [-176.1328125, 84.7060489350415], [-176.1328125, 84.7383871209534], [-176.484375, 84.7383871209534] ] ], [ [ [-175.78125, 84.7383871209534], [-175.78125, 84.7060489350415], [-175.4296875, 84.7060489350415], [-175.4296875, 84.7383871209534], [-175.78125, 84.7383871209534] ] ] ] } '),18);
```
Before:
After:
=> Perf improvement in st asquadint polyfill

modules/quadkey/bigquery/CHANGELOG.md, modules/quadkey/bigquery/sql/ST_BOUNDARY.sql, modules/quadkey/bigquery/test/integration/ST_BOUNDARY.test.js, modules/quadkey/snowflake/test/integration/ST_BOUNDARY.test.js
Fix the following function in BigQuery returns a Linestring:
```sql
SELECT bqcarto.quadkey.ST_BOUNDARY(0);
-- LINESTRING(-180 85.0511287798066, 180 0, -180 -85.0511287798066)
```
However, in Snowflake and Redshift it returns the proper Polygon:
```sql
SELECT ST_ASWKT(sfcarto.quadkey.ST_BOUNDARY(0));
-- POLYGON((-180 85.05112878,-180 -85.05112878,180 -85.05112878,180 85.05112878,-180 85.05112878))
```
=> Boundary issue with quadint 0

modules/h3/snowflake/package.json, modules/h3/snowflake/yarn.lock
Try to fix this kind of problem:
```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/home/runner/work/carto-advanced-spatial-extension/carto-advanced-spatial-extension/core/modules/h3/snowflake/node_modules/h3-js/doc-files/insert-version.js'".
make[4]: *** [../../../common/snowflake/Makefile:46: /home/runner/work/carto-advanced-spatial-extension/carto-advanced-spatial-extension/core/modules/h3/snowflake/node_modules] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [../../../common/snowflake/Makefile:97: deploy] Error 2
make[2]: *** [../../../common/snowflake/Makefile:89: deploy] Error 1
make[1]: *** [Makefile:11: deploy] Error 1
make: *** [Makefile:24: test-integration-full] Error 2
```
=> Remove h3 lib

common/redshift/test_utils/__init__.py
This change was done to allow create and drop tables in test.
As we are creating connections each time a query is created they are running in parallel and not in order.
Adding queries to run_queries will allow us to run queries in order.
I was considering ways to be able to run queries in order on each of the tests. And one would be to keep the connection in the test (even if it's created inside test_utils) and then pass it to run_query as parameter. But wanted to keep it similar to other warehouses.
=> Allow multiple queries in redshift tests

common/redshift/test_unit_utils/__init__.py
Add norm_sql function to aid in unit tests.
Note that unit tests uses venv2, so we can't use `test_utils` in those because it requires libraries only present in venv3.
=> Add utils for unit tests (which use python2)

common/bigquery/test-utils.js
This is handy for comparing result rows in integration tests, given that order may not be specified and float number accuracy may vary.
=> Add util to sort expected rows and round numeric values

modules/quadkey/redshift/lib/__init__.py, modules/quadkey/redshift/sql/__QUADBIN_FROMQUADINT.sql, modules/quadkey/redshift/sql/__QUADINT_RESOLUTION.sql, modules/quadkey/redshift/sql/__QUADKEY_BBOX.sql
I'm adding `__QUADKEY_BBOX(my_qk)` calling directly the internal JS UDFs because when using `QUADINT_BBOX(QUADINT_FROMQUADKEY(my_qk))` Redshift complains about too many nested functions.
I'm using this PR to bring the implementation of `__QUADBIN_FROMQUADINT` to the module quadkey as well.
=> Add redshift tiler dependencies

common/postgres/test_utils/__init__.py
The `dicts_approx_equal` compares dicts and makes comparisons of floats and strings that contain comma-separated lists of numbers approximate (recursively).
=> Add auxiliar methods for PG tests

common/bigquery/create_installation_package.sh
I am doing this just in BQ for the moment. The think is that the LDS header was overwritten by nothing.
=> Concatenate headers instead of overwrite

clouds/bigquery/common/list_functions.js, clouds/bigquery/common/test-utils.js, clouds/snowflake/common/list_functions.js
* Fix globalTeardown file name check
* Replace BQ_PREFIX also in test queries (needed [some cases](https://github.com/CartoDB/analytics-toolbox/blob/master/modules/data/bigquery/test/integration/DATAOBS_ENRICH_POLYGONS.test.js#L162))
=> Small changes in BigQuery reorganization

clouds/databricks/CHANGELOG.md, clouds/databricks/libraries/scala/core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/258281/change-optimized-tables-to-snappy-in-databricks
The tables in the database carto_dev_data with geometries and carto index field (optimized) have been rewritten in snappy.
The default compression has been set to snappy
- Set default compression codec to snappy
- `cd clouds/databricks`
- `make deploy`
- Optimize a table
- The table created must be compressed with snappy
- Create a map of the newly created table in builder
- Create a map of a migrated table
=> change default compression to snappy in databricks optimized tables

clouds/databricks/CHANGELOG.md, clouds/databricks/libraries/scala/Makefile, clouds/databricks/libraries/scala/core/src/main/scala/com/carto/analyticstoolbox/modules/accessors/ST_X.scala, clouds/databricks/libraries/scala/core/src/main/scala/com/carto/analyticstoolbox/modules/accessors/ST_Y.scala, clouds/databricks/libraries/scala/core/src/test/scala/com/carto/analyticstoolbox/modules/constructors/STConstructorsSpec.scala, clouds/databricks/libraries/scala/core/src/test/scala/com/carto/analyticstoolbox/modules/constructors/ST_MakePointTest.scala, clouds/databricks/modules/doc/accessors/ST_X.md, clouds/databricks/modules/doc/accessors/ST_Y.md
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/257910/databricks-at-beta-release-the-st-x-y-function-returns-a-float-instead-of-a-double-type
Detected a bug where the result of the functions ST_X and ST_Y cannot be used as arguments of the function ST_POINT without casting it to DOUBLE.
To fix that, the type returned by those functions is changed to Double
- Change type returned by ST_X and ST_Y to Double
`cd clouds/databricks`
`make deploy`
`make test`
Run the query that was not working in a databricks notebook
```
WITH t AS(
SELECT ST_X(geom) AS long, ST_Y(geom) AS lat FROM carto_dev_data.points_100k limit 100
)
SELECT ST_POINT(long, lat) FROM t
```
=> change type returned by st_x and xt_y to double

clouds/snowflake/common/build_share.js
The bug was caused by some files being linted. The arguments add multiple spaced in between due to line jumps and they were not introduced correctly. I added a regexp replacement to replace multiple spaces by one and remove starting and ending spaces. 
- Fix
1. Navigate to snowflake/modules/.
2. `make deploy-share`.
3. Check that the share contains all the AT core functions running `show grants to share.<SF_PREFIX>ANALYTICS_TOOLBOX;` in the snowflake console.
=> Fix bug with shares deployment in Snowflake

clouds/postgres/common/test_utils/__init__.py
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/260569
- Autolink: [sc-260569]
Small PR to use PG_SCHEMA in the loading and dropping of tables used in the tests. That way we will avoid possible collisions by using the default schema.
- Fix
=> Use PG_SCHEMA to load/drop tables in test utils

clouds/bigquery/modules/doc/h3/H3_INT_TOSTRING.md, clouds/bigquery/modules/doc/h3/H3_STRING_TOINT.md, clouds/snowflake/modules/doc/h3/H3_INT_TOSTRING.md, clouds/snowflake/modules/doc/h3/H3_STRING_TOINT.md
Add SQL documentation reference for:
- BigQuery H3_STRING_TOINT
- BigQuery H3_INT_TOSTRING
- Snowflake H3_STRING_TOINT
- Snowflake H3_INT_TOSTRING
=> docs: add H3 INT/STRING functions reference in BigQuery, Snowflake

clouds/bigquery/modules/doc/clustering/ST_CLUSTERKMEANS.md, clouds/bigquery/modules/doc/constructors/ST_BEZIERSPLINE.md, clouds/bigquery/modules/doc/constructors/ST_MAKEENVELOPE.md, clouds/bigquery/modules/doc/constructors/ST_TILEENVELOPE.md, clouds/bigquery/modules/doc/h3/H3_BOUNDARY.md, clouds/bigquery/modules/doc/h3/H3_DISTANCE.md, clouds/bigquery/modules/doc/h3/H3_FROMGEOGPOINT.md, clouds/bigquery/modules/doc/h3/H3_KRING.md, clouds/bigquery/modules/doc/h3/H3_POLYFILL.md, clouds/bigquery/modules/doc/processing/ST_DELAUNAYLINES.md, clouds/bigquery/modules/doc/processing/ST_POLYGONIZE.md, clouds/bigquery/modules/doc/processing/ST_VORONOIPOLYGONS.md, clouds/bigquery/modules/doc/transformations/ST_BUFFER.md, clouds/bigquery/modules/doc/transformations/ST_CENTERMEAN.md, clouds/bigquery/modules/doc/transformations/ST_GREATCIRCLE.md, clouds/bigquery/modules/doc/transformations/ST_LINE_INTERPOLATE_POINT.md, clouds/snowflake/modules/doc/accessors/ST_ENVELOPE_ARR.md, clouds/snowflake/modules/doc/clustering/ST_CLUSTERKMEANS.md, clouds/snowflake/modules/doc/constructors/ST_MAKEELLIPSE.md, clouds/snowflake/modules/doc/measurements/ST_MINKOWSKIDISTANCE.md, clouds/snowflake/modules/doc/processing/ST_VORONOIPOLYGONS.md, clouds/snowflake/modules/doc/transformations/ST_CENTEROFMASS.md, clouds/snowflake/modules/doc/transformations/ST_GREATCIRCLE.md, clouds/snowflake/modules/doc/transformations/ST_LINE_INTERPOLATE_POINT.md
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/284478
- Autolink: [sc-284478]
"Additional examples" section is now generated in the docs from the example's metadata. This way is more flexible in terms of updates in the examples, links, etc.
=> doc: remove additional examples from the reference

clouds/bigquery/modules/sql/transformations/ST_GREATCIRCLE.sql, clouds/bigquery/modules/test/transformations/ST_GREATCIRCLE.test.js, clouds/redshift/modules/sql/transformations/ST_GREATCIRCLE.sql, clouds/redshift/modules/test/transformations/test_ST_GREATCIRCLE.py, clouds/snowflake/modules/sql/transformations/ST_GREATCIRCLE.sql, clouds/snowflake/modules/test/transformations/ST_GREATCIRCLE.test.js
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/294737/fix-st-greatcircle-crashing-for-endpoint-startpoint
- Autolink: [294737]
I've fixed this issue in all the providers containing greatcircle. I'm returning a `NULL` but returning any of the points could be a good idea as well. I can do the quick change if needed.
In Rs we were returning a LINESTRING with the same point repeated many times which made no sense.
- Fix
```
-- BQ
WITH 
origin AS (
SELECT 
id,insee_code_origine,nom_origine,dep_origine,DT_flux_voiture, distance_vol_oiseau_km,
ST_GEOGPOINT(CAST(lon_origine AS float64),CAST(lat_origine AS float64)) AS geom
FROM cartodb-gcp-solutions-eng-team.mbescansa.od_matrix
) ,
destination AS (
SELECT
id,insee_code_destination,nom_destination,DT_flux_voiture,distance_vol_oiseau_km, …
```
=> fix(bq,sf,rs|transformations): great circle crashing for equal origin and end

clouds/snowflake/modules/doc/h3/H3_RESOLUTION.md, clouds/snowflake/modules/sql/h3/H3_RESOLUTION.sql, clouds/snowflake/modules/test/h3/H3_RESOLUTION.test.js, clouds/snowflake/modules/test/transformations/ST_CONVEXHULL.test.js
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/311338/move-h3-resolution-to-core-in-snowflake
- Autolink: [311338]
- Feature
```
-- Non valid index
select carto_backend_data_team.vdelacruz_carto.H3_RESOLUTION('ff283473fffffff');
-- NULL
-- Valid index
select carto_backend_data_team.vdelacruz_carto.H3_RESOLUTION('84390cbffffffff');
-- 4
```
=> feat(sf|h3): add h3_resolution

clouds/bigquery/modules/sql/quadbin/QUADBIN_FROMLONGLAT.sql, clouds/bigquery/modules/test/quadbin/QUADBIN_FROMLONGLAT.test.js, clouds/postgres/README.md, clouds/postgres/modules/sql/quadbin/QUADBIN_FROMLONGLAT.sql, clouds/postgres/modules/test/quadbin/test_QUADBIN_FROMLONGLAT.py, clouds/redshift/libraries/python/requirements.txt, clouds/redshift/modules/test/quadbin/test_QUADBIN_FROMLONGLAT.py
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/289411
- Autolink: [sc-289411]
Ported Python formula in https://github.com/CartoDB/quadbin-py/blob/master/quadbin/utils.py#L119 to SQL.
Refactor applied to BQ and PG.
Original implementation was slightly different and use of other operators.
Maintained in the current SQL implementation the bitwise version of MODULO function.
- Refactor
- Tests
Please describe how to validate the feature or fix
1. check that any conversion is give the same result as the PY implementation in redshift
- GitHub labels
- Proper status & reviewers
- Tests
=> Chore/sc 289411/update quadbin fromlonglat formula

.github/workflows/bigquery.yml, .github/workflows/databricks.yml, .github/workflows/postgres.yml, .github/workflows/redshift.yml, .github/workflows/snowflake.yml
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/328359/at-deploy-internal-for-ci-in-all-clouds
- Autolink: [sc-328359]
Matrixes were not compatible with secrets so we changed the approach. Now we store secrets ids in the matrix.
- Fix
=> fix(bq,sf,rs,pg,db): fix deploy internal

clouds/bigquery/Makefile, clouds/snowflake/Makefile
Shortcut
- Autolink: [sc-342684]
It seems that in some cases node_modules could include python files. This code update should exclude those files.
- Fix
=> fix(bq,sf): avoid linting node_modules

clouds/bigquery/modules/doc/h3/H3_POLYFILL_MODE.md, clouds/bigquery/modules/doc/h3/H3_POLYFILL_TABLE.md, clouds/bigquery/modules/doc/quadbin/QUADBIN_POLYFILL_TABLE.md, clouds/bigquery/modules/sql/h3/H3_POLYFILL_TABLE.sql, clouds/bigquery/modules/sql/quadbin/QUADBIN_POLYFILL_TABLE.sql, clouds/bigquery/modules/sql/utils/__CHECK_TABLE.sql, clouds/bigquery/modules/sql/utils/__TABLENAME_JOIN.sql, clouds/bigquery/modules/sql/utils/__TABLENAME_SPLIT.sql, clouds/bigquery/modules/test/h3/H3_POLYFILL_TABLE.test.js, clouds/bigquery/modules/test/quadbin/QUADBIN_POLYFILL_TABLE.test.js, clouds/snowflake/modules/doc/h3/H3_POLYFILL_TABLE.md, clouds/snowflake/modules/sql/h3/H3_POLYFILL_TABLE.sql, clouds/snowflake/modules/test/h3/H3_POLYFILL_TABLE.test.js
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/344469
- Autolink: [sc-344469]
Add procedures H3/QUADBIN_POLYFILL_TABLE in BigQuery, H3_QUADBIN_POLYFILL in Snowflake.
- Feature
- Tests
```sql
CALL carto.H3_POLYFILL_TABLE(
"SELECT ST_GEOGFROMTEXT('POLYGON ((-3.71219873428345 40.413365349070865, -3.7144088745117 40.40965661286395, -3.70659828186035 40.409525904775634, -3.71219873428345 40.413365349070865))') AS geom",
9, 'intersects',
'<project>.<dataset>.<output_table>'
);
-- The table `<project>.<dataset>.<output_table>` will be created
-- with column: h3
```
```sql
CALL carto.H3_POLYFILL_TABLE(
'SELECT geom, name, value FROM `<project>.<dataset>.<table>`',
9, 'center',
'<project>.<dataset>.<output_table>'
);
-- The table `<project>.<dataset>.<output_table>` …
```
=> feat(bq,sf|h3,quadbin): add H3/QUADBIN_POLYFILL_TABLE

CONTRIBUTING.md
This is not just a case o code style, we need this to work out dependencies for installation.
=> chore: add contrib notes about naming functions

clouds/bigquery/common/package.json
https://app.shortcut.com/cartoteam/story/342684/at-deploy-timeout-to-me-regions-and-others
There's no dependency issue after upgrading `bigquery` from `^5.3.0` to `^7.3.0` (latest) ✅ 
```
~/git/analytics-toolbox-core/clouds/bigquery$ cat .env
BQ_PREFIX=jarroyo_
BQ_PROJECT=cartodb-data-engineering-team
BQ_BUCKET=gs://bqcartodev
BQ_REGION=us
GOOGLE_APPLICATION_CREDENTIALS=/home/albertoh/.config/gcloud/legacy_credentials/albertoh@cartodb.com/adc.json
BQ_LDS_ENDPOINT=https://lds-func-us-ea1-1942-cmc6qlhtda-ue.a.run.app
BQ_LDS_CONNECTION=cartodb-data-engineering-team.us.jarroyo-test-conn
BQ_API_BASE_URL=https://gcp-us-east1.api.carto.com
BQ_LDS_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhIjoiYWNfNTEyYnI2aG4iLCJqdGkiOiI4NTQ5YzFjNiJ9.6A-kvXaZ6tmMUEPwi590mxg3ghyJ6EY9RAMqMPlGImo …
```
=> chore: update dependency bigquery to 7.3.0

clouds/bigquery/modules/Makefile
Some FIND_TWIN_AREAS tests requires this limit to be increased.
=> chore(bq): increase tests timeout to 200000

clouds/bigquery/modules/sql/h3/H3_POLYFILL_TABLE.sql, clouds/bigquery/modules/test/h3/H3_POLYFILL_TABLE.test.js
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/373790/h3-polyfill-table-in-bq-not-working
- Autolink: [sc-373790]
It seems that we didn't reference an internal function correctly.
- Fix
```
CALL `cartodb-data-engineering-team`.vdelacruz_carto.H3_POLYFILL_TABLE(
'SELECT geom FROM `cartodb-data-engineering-team.vdelacruz_carto.newyork_ooh_sample_audience_h3`',
9, 'center',
'cartodb-data-engineering-team.vdelacruz_carto.newyork_ooh_sample_audience_h3_out'
);
-- WORKS
```
=> fix(bq|h3): fix broken reference in H3_POLYFILL_TABLE

.github/workflows/postgres-ded.yml
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/330620/fix-dedicated-deployments-for-releases-in-atc
- Autolink: [sc-330620]
- Fix
Will have to test on next releases. But the code is the one that we have in Advanced and it was working fine there.
=> chore(pg): fix typo naming dedicated deployments for releases 

.github/workflows/snowflake-ded.yml, clouds/bigquery/modules/sql/constructors/ST_TILEENVELOPE.sql, clouds/bigquery/modules/test/constructors/ST_TILEENVELOPE.test.js, clouds/snowflake/modules/test/constructors/ST_TILEENVELOPE.test.js
The tests on this PR https://github.com/CartoDB/analytics-toolbox-core/pull/466 are failing due to recent updates in the default values of QUADBIN functions. Snowflake QUADBIN UDFs now return NULL for NULL arguments as it happens in Bigquery and as it was happening in some Quadbin Snowflake UDFs.
After seen the tests failing, I've discovered that in Bigquery we were still using the deprecated QUADINT functions to calculate the tile envelope.
Now ST_TILEENVELOPE returns `NULL` for null arguments. Unless we explicitly want to trigger an error.
- Refactor
=> chore(bs,sf|constructors): update internal function used by ST_TILEENVELOPE

.github/workflows/snowflake-ded.yml, clouds/bigquery/common/run-script.js, clouds/bigquery/modules/Makefile, clouds/bigquery/modules/sql/constructors/ST_TILEENVELOPE.sql, clouds/bigquery/modules/test/constructors/ST_TILEENVELOPE.test.js, clouds/postgres/common/run_script.py, clouds/postgres/modules/Makefile, clouds/redshift/common/run_script.py, clouds/redshift/modules/Makefile, clouds/snowflake/common/run-script.js, clouds/snowflake/modules/Makefile, clouds/snowflake/modules/test/constructors/ST_TILEENVELOPE.test.js
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/237106/safe-make-remove-command
- Autolink: [sc-237106]
I've reused the function run-script allowing to pass parameters as it seemed like a cleaner solution.
- Refactor
I've tested dropping all the functions in my schema in all providers.
=> chore(bq,sf,rs,pg): make remove drop functions instead of whole schema

clouds/snowflake/common/build_native_app_setup_script.js, clouds/snowflake/modules/Makefile
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/377459/publish-analytics-toolbox-native-app-in-snowflake
- Autolink: [sc-377459]
Adding tables requires some changes on the infra. I set it up so only when `production=1` is added the tables are included in the build.
- Refactor
=> chore(sf): add additional tables to native apps

clouds/bigquery/modules/doc/transformations/ST_DESTINATION.md, clouds/redshift/modules/doc/transformations/ST_DESTINATION.md, clouds/snowflake/modules/doc/transformations/ST_DESTINATION.md
Shortcut
As mentioned on this issue: https://github.com/CartoDB/analytics-toolbox-core/issues/474 the doc on ST_DESTINATION does not correspond with the actual implementation. It seems like a bug introduced by us because the extra information is not included in turf docs.
Just performed the same test described in the ticket.
=> docs(bs,sf,rs|transformations): fix ST_DESTINATION bearing parameter description

clouds/snowflake/common/package.json
Shortcut
It seems that the [latest release](https://docs.snowflake.com/en/release-notes/clients-drivers/nodejs-2024#version-1-10-0-february-27-2024) of the snowflake driver for js is causing the CI and CD to break. For this reason I am fixing the version to the previous one to that `1.9.3`.
```
{"level":"INFO","message":"[5:09:00.151 PM]: Trying to initialize Easy Logging"}
Unable to perform operation because a connection was never established.
{"level":"INFO","message":"[5:09:00.171 PM]: No client config file found in default directories"}
{"level":"INFO","message":"[5:09:00.172 PM]: Easy Logging is disabled as no config has been found"}
{"level":"INFO","message":"[5:09:01.035 PM]: Trying to initialize Easy Logging"}
ERROR: Unable to perform operation because a connection was never …
```
=> fix(sf): CI and CD not working because of snowflake driver breaking changes

.github/workflows/redshift-ded.yml, clouds/bigquery/modules/Makefile, clouds/postgres/modules/Makefile, clouds/redshift/modules/Makefile, clouds/snowflake/modules/Makefile
Shortcut
I've noticed that with my changes in: https://github.com/CartoDB/analytics-toolbox-core/pull/466 when dedicateds were removed, only the functions were removed instead of the whole schema.
I've restored `make remove` as it was before and added `make remove-functions` to only removed functions for development purposes.
Also have found bug in redshift dedicateds.
- Fix
Tested to run in the different providers/modules folder:
```
make remove-functions
```
Also tried to create and remove dedicated and see how the schemas gets removed.
=> fix(bq,sf,rs,pg): drop schemas when dedicateds gets released

clouds/bigquery/modules/doc/processing/ST_DELAUNAYLINES.md, clouds/bigquery/modules/doc/processing/ST_DELAUNAYPOLYGONS.md, clouds/bigquery/modules/doc/processing/ST_VORONOILINES.md, clouds/bigquery/modules/doc/processing/ST_VORONOIPOLYGONS.md, clouds/redshift/modules/doc/processing/ST_DELAUNAYLINES.md, clouds/redshift/modules/doc/processing/ST_DELAUNAYPOLYGONS.md, clouds/redshift/modules/doc/processing/ST_VORONOILINES.md, clouds/redshift/modules/doc/processing/ST_VORONOIPOLYGONS.md, clouds/snowflake/modules/doc/processing/ST_DELAUNAYLINES.md, clouds/snowflake/modules/doc/processing/ST_DELAUNAYPOLYGONS.md, clouds/snowflake/modules/doc/processing/ST_VORONOILINES.md, clouds/snowflake/modules/doc/processing/ST_VORONOIPOLYGONS.md
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/397997/internal-st-voronoi-running-into-memory-limitations#activity-398943
- Autolink: [sc-397997]
Added the doc described in the ticked about Voronoi limitation for Bigquery, Snowflake and Redshift.
In Redshift for now it doesn't make a lot of sense because users will face first the VARCHAR size limitation. But for consistency and in case Redshift upgrades the size I've included it there too.
=> docs(bq,sf,rs|processing): update voronoi doc

.github/workflows/snowflake.yml, LICENSE, clouds/bigquery/common/DROP_FUNCTIONS.sql, clouds/postgres/common/DROP_FUNCTIONS.sql, clouds/redshift/common/DROP_FUNCTIONS.sql, clouds/snowflake/Makefile, clouds/snowflake/common/DROP_FUNCTIONS.sql, clouds/snowflake/common/Makefile
- Make `create-package` command not dependent on SF_DATABASE variable.
- Update licenses year to 2024 in all required files and headers.
=> chore: update snowflake create-package and licenses year

clouds/postgres/common/test_utils/__init__.py
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/409939
- Autolink: [sc-409939]
Please include a summary of the change. If required, also include relevant info about motivation and context... And if PR includes UI elements (or if it helps for understanding it), please add extra files: snapshots, videos...
- Fix
To recreate issue:
1. Set PG_USER's password to include `%` character
2. From the  `analytics-toolbox` project, run `cd clouds/postgres && make test`
3. It will fail due to a bad password in the connection_string in submodule `core/clouds/postgres/common/test_utils/__init__.py
4. Checkout this branch in `core` and rerun. The tests should run fine
=> Fix DB Connection Error in tests when % character in PG_PASSWORD

clouds/postgres/common/python3_requirements.txt
Shortcut
- Story:https://app.shortcut.com/cartoteam/story/434862/pg-pandas-geopandas-are-incompatible-with-new-numpy-2-x-x-releases-breaking-c-api-changes
- Autolink: [sc-434862]
Pandas doesn't fully support numpy 2+ . Our unit tests encounter a breaking change with the C API.
```
make[1]: Entering directory '/home/dean/development/analytics-toolbox/clouds/postgres'
make[2]: Entering directory '/home/dean/development/analytics-toolbox/clouds/postgres/libraries/javascript'
make[2]: Leaving directory '/home/dean/development/analytics-toolbox/clouds/postgres/libraries/javascript'
make[1]: Leaving directory '/home/dean/development/analytics-toolbox/clouds/postgres'
make[1]: Entering directory '/home/dean/development/analytics-toolbox/clouds/postgres'
make[2]: Entering directory …
```
=> fix(pg): lock numpy to v1.24.4 until pandas supports 2.X.X

clouds/bigquery/modules/Makefile
It seems that some tests (`FIND_TWIN_AREAS`  and  `FIND_SIMILAR_LOCATIONS`) are failing because of timeouts.
=> chore(bq): increse jest timeout to 30000

clouds/snowflake/native_app/README.md
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/438973/add-documentation-on-how-to-update-the-native-app-in-snowflake
- Autolink: [sc-438973]
Tested the process with a local installation.
=> docs(sf): add docs on how to update the analytics toolbox from a native app

clouds/snowflake/native_app/SETUP_SCRIPT.sql
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/441537/update-python-version-in-snowflake-procedures
- Autolink: [sc-441537]
We have received a message from the Snowflake team that using the version 3.8 will get depecrated in stored procedures.
- Fix
- Checked that the Native app was succesfully installed locally.
=> chore(sf): update python version on stored procedures from 3.8 to 3.9

clouds/snowflake/modules/doc/h3/H3_POLYFILL_TABLE.md
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/458801/update-docs-for-h3-polyfill-table-to-only-support-polygons-in-snowflake
- Autolink: [sc-458801]
=> docs(sf|h3): update h3_polyfill_table docs as it does not support points or lines

clouds/bigquery/modules/sql/h3/H3_POLYFILL.sql, clouds/bigquery/modules/sql/quadbin/QUADBIN_POLYFILL.sql
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/464369/at-bq-polyfill-quadbin-for-geometries-with-holes-fails
- Autolink: [sc-464369]
This error started to happen because of `ST_BOUNDINGBOX` in Bigquery not working properly with polygons containing holes anymore. I used the internal `ST_ENVELOPE` function instead of `ST_EXTERIORRING` even if it's a JS function because `ST_EXTERIORRING` is crashing for multypolygons.
- Fix
The CI was also failing but thanks to this fix it should be green now.
```
with geo as (
select ST_GEOGFROMTEXT('POLYGON((-5.73685493950322 41.5045088398422, -5.73685483649725 41.4674462934938, -5.73685137730796 41.4674199761992, -5.73684113282628 41.4673946702735, -5.73682449674882 41.4673713482076, -5.73680210839533 41.4673509062528, -5.73677482813928 …
```
=> fix(bq|h3,quadbin): H3_POLYFILL and QUADBIN_POLYFILL functions not working with holes

clouds/bigquery/common/build_modules.js, clouds/bigquery/common/list_libraries.js
Shortcut
- Story: https://app.shortcut.com/cartoteam/story/463939/split-js-libraries-creation-into-different-files-in-bigquery
- Autolink: [sc-463939]
This should be part of this other PR: https://github.com/CartoDB/analytics-toolbox-core/pull/541
- Refactor
Tested by deploying in local some raster functions that includes multiple libraries.
https://github.com/CartoDB/analytics-toolbox/pull/930
=> chore(bq): allow supporting multiple libraries in one line

clouds/snowflake/common/Makefile
Shortcut
By doing some tests with Trial accounts detected that the host is no longer identified by `account.region`, the account identifier can be `organizationname-accountname`. For instance: HDKHROX-VAB74276. This fix unblock deployment into trial accounts.
- Refactor
Tested it by deploying locally.
=> chore(sf): SF_ACCOUNT no longer follows "account.region" format
