sql/quadkey/locationToQuadkey.sql

@jatorre, I found this bug while trying to use this function

fixes variable reference error

---

libs/s2geometry.js
sql/s2/ST_S2.sql
sql/s2/latLngToId.sql
sql/s2/latLngToKey.sql

fix for the error mentioned here for the s2geometry lib on BQ:
https://github.com/CartoDB/bigquery-jslibs/issues/1#issuecomment-581499680

s2-error-fixes

---

libs/quadkey.js

In https://github.com/CartoDB/bigquery-jslibs/pull/13 I introduced BigInt to solve some issues with high level zooms, but that made things ~10x slower. This modifies the code to only use BigInt (or int Numbers when bitwise operators are not needed) for detail >= 31, and otherwise use Numbers (with 32 int bit operators).

Quadkey: Only use bigint when necessary

---

.github/CODEOWNERS
.github/workflows/ci.yml

https://app.clubhouse.io/cartoteam/story/134079/add-ci-auth-tokens-to-the-extension-public-repository

add public ci

---

quadkey/bq/sql/VERSION.sql
quadkey/bq/test/quadkey_integration.js
quadkey/library/js/quadkey_version.js
quadkey/library/test/quadkey_test.js

This is done for consistency with other modules.

update version type

---

quadkey/bq/sql/KRING.sql
quadkey/bq/sql/ST_ASQUADINT.sql
quadkey/bq/sql/ST_ASQUADINTPOLYFILL.sql
quadkey/bq/sql/TOCHILDREN.sql
quadkey/bq/sql/TOPARENT.sql
quadkey/bq/test/st_polyfill_integration.js
s2/bq/sql/ST_ASID.sql

We were getting wrong values in quadint_polyfill, after investigating a bit further I saw that some int parsing were missing.

Fix st asquadint polyfill

---

.github/workflows/ci.yml
.github/workflows/deploy-staging.yml
h3/Makefile
placekey/Makefile
quadkey/Makefile
s2/Makefile
skel/Makefile
tools/setool/lib/create-module/generator.js
transformation/Makefile

- Add `deploy_st` tag to deploy staging
- Improve `run_ci` logic
- Add dir-check in `make clean`

Add deploy_st tag to deploy staging 

---

modules/constructors/snowflake/sql/ST_BEZIERSPLINE.sql
modules/measurements/snowflake/sql/ST_ANGLE.sql
modules/measurements/snowflake/sql/ST_AZIMUTH.sql
modules/processing/snowflake/sql/ST_POLYGONIZE.sql

- Fix some private functions eligible for sharing. 
- Fix one public function not eligible for sharing.

fix shares issues

---

modules/geohash/bigquery/CHANGELOG.md
modules/geohash/bigquery/Makefile
modules/geohash/bigquery/README.md
modules/geohash/bigquery/doc/ST_BOUNDARY.md
modules/geohash/bigquery/doc/VERSION.md
modules/geohash/bigquery/doc/_INTRO.md
modules/geohash/bigquery/lib/index.js
modules/geohash/bigquery/package.json
modules/geohash/bigquery/sql/ST_BOUNDARY.sql
modules/geohash/bigquery/sql/VERSION.sql
modules/geohash/bigquery/test/integration/ST_BOUNDARY.test.js
modules/geohash/bigquery/test/integration/VERSION.test.js
modules/geohash/bigquery/test/unit/index.test.js

Add geohash module and ST_BOUNDARY function

---

common/snowflake/Makefile
scripts/modulesort.js

See https://github.com/CartoDB/carto-advanced-spatial-extension/pull/127

Create installation package for Snowflake

---

modules/h3/snowflake/package.json
modules/h3/snowflake/yarn.lock

Adding the dependency back as it must be breaking H3

Add h3-js to H3 in snowflake

---

Makefile
common/bigquery/Makefile
common/bigquery/yarn.lock
common/snowflake/Makefile
common/snowflake/yarn.lock
modules/accessors/bigquery/yarn.lock
modules/h3/bigquery/yarn.lock
modules/placekey/bigquery/yarn.lock
modules/quadkey/shared/javascript/yarn.lock
modules/s2/bigquery/yarn.lock

- Add make install command
- Upgrade checksums in yarn install
- Clean yarn cache in make clean
- Update yarn.lock files

Improve yarn install

---

.github/workflows/deploy-production.yml

https://app.shortcut.com/cartoteam/story/193828/telus-create-analytics-toolbox-project-in-northamerica-northeast1

Adding carto-un-na-ne1 project

---

.github/workflows/deploy-production.yml

Fix Analytics Toolbox listing in Snowflake [sc-201780]

Update the share used for Snowflake

---

.github/workflows/deploy-production.yml

Story details: https://app.shortcut.com/cartoteam/story/214344

Create analytics toolbox project in asia-southeast1

---

common/bigquery/yarn.lock
common/snowflake/yarn.lock

- https://github.com/CartoDB/carto-analytics-toolbox-core/pull/214
- https://github.com/CartoDB/carto-analytics-toolbox-core/pull/215
- https://github.com/CartoDB/carto-analytics-toolbox-core/pull/220

Add dependabot security fixes

---

README.md

Added a section to strat using them directly so that I can link them from the H3 bindings page.

Added a section to strat using them directly

---

clouds/postgres/.env.template
clouds/postgres/README.md
clouds/redshift/.env.template
clouds/redshift/README.md
clouds/redshift/common/Makefile
clouds/redshift/libraries/python/Makefile
clouds/snowflake/.env.template
clouds/snowflake/README.md
clouds/snowflake/common/DROP_FUNCTIONS.sql
clouds/snowflake/common/Makefile

Review env vars documentation. Add regex checks for some: host, bucket, account.

Check env variables with regex

---

clouds/databricks/libraries/scala/.scalafix.conf
clouds/databricks/libraries/scala/build.sbt

- Aggregate jts subproject to root in databricks cloud

aggregate jts subproject

---

.github/workflows/bigquery-ded.yml
.github/workflows/postgres-ded.yml
.github/workflows/redshift-ded.yml
.github/workflows/snowflake-ded.yml
clouds/bigquery/modules/doc/accessors/ST_ENVELOPE.md

Story details: https://app.shortcut.com/cartoteam/story/258215

Review ded workflow variables

---

clouds/snowflake/common/test-utils.js

Needed by test in https://github.com/CartoDB/analytics-toolbox/pull/485

Replace SF_SCHEMA in test queries

---

.github/workflows/databricks.yml

Shortcut
- Story: https://app.shortcut.com/cartoteam/story/254519
- Autolink: [sc-254519]
Inject databricks token from a terraform managed Google Secret

Add DB token from Google secret manager

---

.github/workflows/bigquery.yml
.github/workflows/databricks.yml
.github/workflows/postgres.yml
.github/workflows/redshift.yml
.github/workflows/snowflake.yml
clouds/bigquery/Makefile
clouds/databricks/.env.template
clouds/databricks/Makefile
clouds/databricks/README.md
clouds/databricks/common/Makefile
clouds/databricks/common/python_utils/run_query.py
clouds/databricks/common/submit-run-template.json
clouds/databricks/modules/Makefile
clouds/postgres/Makefile
clouds/redshift/Makefile
clouds/snowflake/Makefile

Shortcut
- Story: https://app.shortcut.com/cartoteam/story/266416
- Fix

Several fixes in CI/CD

---

clouds/databricks/common/sql_lint.py

- improve sql_lint for empty sql dir in databricks

improve sql_lint for empty sql dir in databricks

---

.github/workflows/publish-release.yml

fix: fix release jobs reference

---

.github/workflows/bigquery.yml
.github/workflows/databricks.yml
.github/workflows/postgres.yml
.github/workflows/snowflake.yml
clouds/databricks/libraries/scala/build.sbt

Add production flag so the AT is deployed internally as in production. This make it testable from CARTO's interface.

Deploy production version internally

---

clouds/bigquery/modules/Makefile

Tests where crashing in this other PR because of jest timeouts.
https://github.com/CartoDB/analytics-toolbox/pull/558

Bigquery increase jest timeout

---

clouds/snowflake/libraries/javascript/libs/transformations_convex.js
clouds/snowflake/libraries/javascript/test/transformations.test.js
clouds/snowflake/modules/doc/transformations/ST_CONVEXHULL.md
clouds/snowflake/modules/sql/transformations/ST_CONVEXHULL.sql
clouds/snowflake/modules/test/transformations/ST_CONVEXHULL.test.js

Shortcut
- Story: https://app.shortcut.com/cartoteam/story/308159
- Autolink: [sc-308159]
Implement the ST_CONVEXHULL in Snowflake function as a feature request.
- Feature
- Tests

feat(sf|transformations): add ST_CONVEXHULL function

---

clouds/snowflake/common/test-utils.js

For use in https://github.com/CartoDB/analytics-toolbox/pull/630

Add test util to check for table existence

---

clouds/bigquery/modules/sql/quadbin/QUADBIN_POLYFILL.sql
clouds/postgres/modules/sql/quadbin/QUADBIN_POLYFILL.sql

Story details: https://app.shortcut.com/cartoteam/story/289411

 chore(bq|pg): [sc-289411] Update QUADBIN_FROMLONGLAT formula convergint to PY/JS imlementation

---

clouds/bigquery/common/run-script.js
clouds/postgres/common/run_script.py
clouds/snowflake/common/run-script.js

Shortcut
- Story: https://app.shortcut.com/cartoteam/story/323212/add-option-to-not-deploy-sql-1-by-1
- Autolink: [sc-323212]
Please include a summary of the change. If required, also include relevant info about motivation and context... And if PR includes UI elements (or if it helps for understanding it), please add extra files: snapshots, videos...
- Refactor
```
-- BIGQUERY
---- Before
% time make deploy           
Building modules...
- Build all
Write /Users/vdelacruz/Desktop/Repositories/analytics-toolbox/clouds/bigquery/modules/build/modules.sql
Deploying modules...
100%|████████████████████████████████████████████████████████████| 329/329 [4m37s<0s]
make deploy  5.28s user 0.64s system 2% cpu 4:40.31 total
---- After
% time make deploy
Building modules...
- Build all
Write …
```

chore(bq,sf,pg): allow deploying all at once

---

.github/workflows/redshift.yml

We were missing some refactors in the deploy-internal
- Fix

fix(rs): fix redshift actions not working with python2

---

clouds/snowflake/modules/doc/transformations/ST_CONCAVEHULL.md

Shortcut
- Story: https://app.shortcut.com/cartoteam/story/303448
- Autolink: [sc-303448]
- 

added example using array_agg for concave hull in SF

---

clouds/postgres/Makefile
clouds/redshift/Makefile

Shortcut
Same as: https://github.com/CartoDB/analytics-toolbox-core/pull/445
- Fix

fix(rs,pg): avoid linting node_modules

---

clouds/bigquery/common/package.json
clouds/postgres/common/package.json
clouds/snowflake/common/package.json

Solves issues when running tests from some MAC M1.
- Fix

fix(bq,sf,pg): update jest version

---

clouds/bigquery/common/build_modules.js

Shortcut
- Story: https://app.shortcut.com/cartoteam/story/STORY_ID
- Autolink: [sc-STORY_ID]
Please include a summary of the change. If required, also include relevant info about motivation and context... And if PR includes UI elements (or if it helps for understanding it), please add extra files: snapshots, videos...
- Fix
- Feature
- Refactor
- Tests
Please describe how to validate the feature or fix
1. go to X
2. test Y
3. assert Z
- Good PR name
- Shortcut link
- Just one issue per PR
- GitHub labels
- Proper status & reviewers
- Tests

fix(bq) SETUP dependencies

---

clouds/bigquery/modules/doc/constructors/ST_MAKEELLIPSE.md
clouds/redshift/modules/doc/constructors/ST_MAKEELLIPSE.md
clouds/snowflake/modules/doc/constructors/ST_MAKEELLIPSE.md

Shortcut
Even if we comply with turf internal docs: https://www.npmjs.com/package/@turf/ellipse
This small change should be compliant with the results returned by ST_MAKEELLIPSE.

docs(bq,sf,rs|): fix ST_MAKEELLIPSE angle docs

---

clouds/snowflake/.env.template
clouds/snowflake/common/run-query.js
clouds/snowflake/common/run-script.js

Shortcut
- Story: https://app.shortcut.com/cartoteam/story/329793
- Autolink: [sc-329793]

feat(sf): added warehouse option for SF

---

clouds/redshift/common/test_utils/__init__.py

Fix `run_query` function for unit tests by enabling autocommit.
- Fix

fix(rs): set autocommit in run_query function
